/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package car.hire.view;

/**
 *
 * @author DELL i5
 */
public class CarBodyPanel extends javax.swing.JPanel {

    /**
     * Creates new form CarBodyPanel
     */
    public CarBodyPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vNumberText1 = new javax.swing.JTextField();
        vNumberLabel1 = new javax.swing.JLabel();
        addCarLabel = new javax.swing.JLabel();
        vIdLabel = new javax.swing.JLabel();
        vNumberText = new javax.swing.JTextField();
        vNumberLabel = new javax.swing.JLabel();
        vModelText = new javax.swing.JTextField();
        vModelLabel = new javax.swing.JLabel();
        vBrandText = new javax.swing.JTextField();
        vBrandLabel = new javax.swing.JLabel();
        vYearLabel = new javax.swing.JLabel();
        vPricePDayText = new javax.swing.JTextField();
        vPricePDayLabel = new javax.swing.JLabel();
        addCarButton = new javax.swing.JButton();
        vIDText = new javax.swing.JTextField();
        vYearChooser = new com.toedter.calendar.JYearChooser();
        chassisNoLabel = new javax.swing.JLabel();
        chassisNoText = new javax.swing.JTextField();

        vNumberLabel1.setText("Vehicle Number");

        setBackground(new java.awt.Color(204, 255, 204));

        addCarLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addCarLabel.setText("Register New Car");

        vIdLabel.setText("Vehicle ID");

        vNumberLabel.setText("Vehicle Number");

        vModelLabel.setText("Model");

        vBrandLabel.setText("Brand");

        vYearLabel.setText("Year");

        vPricePDayLabel.setText("Price Per Day");

        addCarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addCarButton.setText("Add Car");

        chassisNoLabel.setText("Chassis No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vModelLabel)
                                    .addComponent(vBrandLabel)
                                    .addComponent(vYearLabel)
                                    .addComponent(vIdLabel)
                                    .addComponent(vNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(vNumberText, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(vIDText))
                                    .addComponent(vPricePDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vModelText, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                    .addComponent(chassisNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vBrandText))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addCarButton)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vPricePDayLabel)
                            .addComponent(chassisNoLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addCarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vIdLabel)
                    .addComponent(vIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vModelLabel)
                    .addComponent(vModelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vBrandLabel)
                    .addComponent(vBrandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vYearLabel)
                    .addComponent(vYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chassisNoLabel)
                    .addComponent(chassisNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vPricePDayLabel)
                    .addComponent(vPricePDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(addCarButton)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton addCarButton;
    protected javax.swing.JLabel addCarLabel;
    private javax.swing.JLabel chassisNoLabel;
    private javax.swing.JTextField chassisNoText;
    private javax.swing.JLabel vBrandLabel;
    private javax.swing.JTextField vBrandText;
    private javax.swing.JTextField vIDText;
    private javax.swing.JLabel vIdLabel;
    private javax.swing.JLabel vModelLabel;
    private javax.swing.JTextField vModelText;
    private javax.swing.JLabel vNumberLabel;
    private javax.swing.JLabel vNumberLabel1;
    private javax.swing.JTextField vNumberText;
    private javax.swing.JTextField vNumberText1;
    private javax.swing.JLabel vPricePDayLabel;
    private javax.swing.JTextField vPricePDayText;
    private com.toedter.calendar.JYearChooser vYearChooser;
    private javax.swing.JLabel vYearLabel;
    // End of variables declaration//GEN-END:variables

}
