/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package car.hire.view;

import car.hire.controller.CarController;
import car.hire.dto.CarDto;
import car.hire.entity.CarCategoryEntity;
import java.time.LocalDate;
import java.time.Period;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL i5
 */
public class CarBodyPanel1 extends javax.swing.JPanel {

    CarController carController;

    /**
     * Creates new form CarBodyPanel
     */
    public CarBodyPanel1() {
        initComponents();
        carController = new CarController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCarLabel = new javax.swing.JLabel();
        vNumberText = new javax.swing.JTextField();
        vNumberLabel = new javax.swing.JLabel();
        vModelLabel = new javax.swing.JLabel();
        vBrandText = new javax.swing.JTextField();
        vBrandLabel = new javax.swing.JLabel();
        vYearLabel = new javax.swing.JLabel();
        vPricePDayText = new javax.swing.JTextField();
        vPricePDayLabel = new javax.swing.JLabel();
        addCarButton = new javax.swing.JButton();
        vYearChooser = new com.toedter.calendar.JYearChooser();
        vChassisNoLabel = new javax.swing.JLabel();
        vChassisNoText = new javax.swing.JTextField();
        vCategoryIdLabel = new javax.swing.JLabel();
        vCategoryIdText = new javax.swing.JTextField();
        vModelText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        vCategoryDataLabel = new javax.swing.JLabel();
        vColourLabel = new javax.swing.JLabel();
        vColourText = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        addCarLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addCarLabel.setText("Register New Car");

        vNumberLabel.setText("Vehicle Number");
        vNumberLabel.setPreferredSize(new java.awt.Dimension(85, 22));

        vModelLabel.setText("Model");
        vModelLabel.setPreferredSize(new java.awt.Dimension(34, 22));

        vBrandLabel.setText("Brand");
        vBrandLabel.setPreferredSize(new java.awt.Dimension(31, 22));

        vYearLabel.setText("Year");
        vYearLabel.setPreferredSize(new java.awt.Dimension(23, 22));

        vPricePDayLabel.setText("Price Per Day");
        vPricePDayLabel.setPreferredSize(new java.awt.Dimension(69, 22));

        addCarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addCarButton.setText("Add Car");
        addCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarButtonActionPerformed(evt);
            }
        });

        vChassisNoLabel.setText("Chassis No");
        vChassisNoLabel.setPreferredSize(new java.awt.Dimension(58, 22));

        vCategoryIdLabel.setText("Category ID");
        vCategoryIdLabel.setPreferredSize(new java.awt.Dimension(62, 22));

        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.setPreferredSize(new java.awt.Dimension(72, 22));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        vCategoryDataLabel.setPreferredSize(new java.awt.Dimension(50, 22));

        vColourLabel.setText("Colour");
        vColourLabel.setPreferredSize(new java.awt.Dimension(69, 22));

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vCategoryIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(vNumberText, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                        .addComponent(vYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vModelText)
                                        .addComponent(vBrandText, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(vCategoryIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vCategoryDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vChassisNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vPricePDayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vChassisNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vPricePDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(vBrandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vColourText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addCarButton)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addCarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vCategoryIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vCategoryIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vCategoryDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vModelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vBrandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vBrandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vColourText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vChassisNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vChassisNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vPricePDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vPricePDayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCarButton)
                    .addComponent(backButton))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarButtonActionPerformed
        addNewCar();
    }//GEN-LAST:event_addCarButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

    }//GEN-LAST:event_backButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchCarCategoryDto();
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarButton;
    private javax.swing.JLabel addCarLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel vBrandLabel;
    private javax.swing.JTextField vBrandText;
    public javax.swing.JLabel vCategoryDataLabel;
    private javax.swing.JLabel vCategoryIdLabel;
    private javax.swing.JTextField vCategoryIdText;
    private javax.swing.JLabel vChassisNoLabel;
    private javax.swing.JTextField vChassisNoText;
    private javax.swing.JLabel vColourLabel;
    private javax.swing.JTextField vColourText;
    private javax.swing.JLabel vModelLabel;
    private javax.swing.JTextField vModelText;
    private javax.swing.JLabel vNumberLabel;
    private javax.swing.JTextField vNumberText;
    private javax.swing.JLabel vPricePDayLabel;
    private javax.swing.JTextField vPricePDayText;
    private com.toedter.calendar.JYearChooser vYearChooser;
    private javax.swing.JLabel vYearLabel;
    // End of variables declaration//GEN-END:variables

    private void searchCarCategoryDto() {
        try {
            Integer carId = Integer.valueOf(vCategoryIdText.getText());
            CarCategoryEntity entity = carController.getCarCategoryEntity(carId);
            if (entity == null) {
                vCategoryDataLabel.setText("Wrong Car Category ID");
            } else {
                vCategoryDataLabel.setText(entity.getName());
            }

        } catch (Exception ex) {
            Logger.getLogger(CarBodyPanel1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void addNewCar() {

        if (vNumberText.getText().equals("") || vPricePDayText.getText().equals("") || vCategoryIdText.getText().equals("") || vBrandText.getText().equals("") || vModelText.getText().equals("") || vChassisNoText.getText().equals("") || vColourText.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fullyfill Car details");
        } else if (validateNumber(vNumberText.getText())) {
            
            if (validateYear(vYearChooser.getYear())) {
                
                try {
                Integer carId = Integer.valueOf(vCategoryIdText.getText());
                CarDto carDto = new CarDto(
                        null,
                        vNumberText.getText(),
                        carController.getCarCategoryEntity(carId),
                        vModelText.getText(),
                        vBrandText.getText(),
                        vYearChooser.getValue(),
                        vColourText.getText(),
                        vChassisNoText.getText(),
                        Double.valueOf(vPricePDayText.getText()));

                String result = carController.addNewCar(carDto);
                JOptionPane.showMessageDialog(this, result);
                clearPanel();
            } catch (Exception ex) {
                Logger.getLogger(CarBodyPanel1.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            } else {
                JOptionPane.showMessageDialog(this, "Wrong Year");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Your vehicle number is Invalid.\nUse XXX-0000 or XX-0000 pattern");
        }

    }

    private void clearPanel() {
        vNumberText.setText("");
        vCategoryIdText.setText("");
        vModelText.setText("");
        vBrandText.setText("");
        vColourText.setText("");
        vChassisNoText.setText("");
        vPricePDayText.setText("");
        vCategoryDataLabel.setText("");
    }

    public static boolean validateYear(int year) {
        LocalDate now = LocalDate.now();
        int nowYear = now.getYear();
        if (year < nowYear) {
            return true;
        } else {
            return false;
        }

    }

    public static boolean validateNumber(String number) {
        int length = number.length();

        if (length == 7) {
            char firstChar = number.charAt(2);

            for (int i = 3; i < 7; i++) {
                char currentChar = number.charAt(i);
                if (currentChar < '0' || '9' < currentChar) {
                    return false;
                } else {
                    if (firstChar == '-') {
                        return true;
                    } else {
                        return false;
                    }
                }
            }

        } else if (length == 8) {
            char firstChar = number.charAt(3);

            for (int i = 4; i < 8; i++) {
                char currentChar = number.charAt(i);
                if (currentChar < '0' || '9' < currentChar) {
                    return false;
                } else {
                    if (firstChar == '-') {
                        return true;
                    } else {
                        return false;
                    }
                }
            }

        } else {
            return false;
        }
        return false;

    }

}
