/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package car.hire.view;

import car.hire.controller.CarController;
import car.hire.dto.CarDto;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL i5
 */
public class CarPanel extends javax.swing.JPanel {

    CarController carController;

    /**
     * Creates new form CarPanel
     */
    public CarPanel() {
        initComponents();
        carController = new CarController();
        loadCarTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cBodyPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();
        addCarButton = new javax.swing.JButton();
        updateCarButton = new javax.swing.JButton();
        deleteCarButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("  Manage Cars");

        cBodyPanel.setBackground(new java.awt.Color(204, 255, 204));

        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        carTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(carTable);

        addCarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addCarButton.setText("Add New Car");
        addCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarButtonActionPerformed(evt);
            }
        });

        updateCarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateCarButton.setText("Update Car");
        updateCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCarButtonActionPerformed(evt);
            }
        });

        deleteCarButton.setBackground(new java.awt.Color(255, 153, 153));
        deleteCarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteCarButton.setText("Delete Car");
        deleteCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCarButtonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Cars", "Rented Cars", "Available Cars" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout cBodyPanelLayout = new javax.swing.GroupLayout(cBodyPanel);
        cBodyPanel.setLayout(cBodyPanelLayout);
        cBodyPanelLayout.setHorizontalGroup(
            cBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cBodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cBodyPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cBodyPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addCarButton)
                        .addGap(21, 21, 21))
                    .addGroup(cBodyPanelLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        cBodyPanelLayout.setVerticalGroup(
            cBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cBodyPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(cBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCarButton)
                    .addComponent(updateCarButton)
                    .addComponent(deleteCarButton))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cBodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cBodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCarButtonActionPerformed
        deleteCar();
    }//GEN-LAST:event_deleteCarButtonActionPerformed

    private void addCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarButtonActionPerformed
        loadCarBodyPanel1();
    }//GEN-LAST:event_addCarButtonActionPerformed

    private void updateCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCarButtonActionPerformed
        Integer carId = 0;
        
        try {
            carId = getCarId();
            
            if (carId != 0) {
                
                loadCarBodyPanel2(carId);
                
            } else {
                JOptionPane.showMessageDialog(this, "Car not found");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please select a Car from the table before update");
        }
        
        
    }//GEN-LAST:event_updateCarButtonActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        loadCarTable();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void carTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carTableMouseClicked
        Integer carId = getCarId();
    }//GEN-LAST:event_carTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarButton;
    private javax.swing.JPanel cBodyPanel;
    private javax.swing.JTable carTable;
    private javax.swing.JButton deleteCarButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateCarButton;
    // End of variables declaration//GEN-END:variables

    private void loadCarBodyPanel1() {
        cBodyPanel.removeAll();
        CarBodyPanel1 carBodyPanel1 = new CarBodyPanel1();
        carBodyPanel1.setSize(cBodyPanel.getWidth(), cBodyPanel.getHeight());
        cBodyPanel.add(carBodyPanel1);
        cBodyPanel.repaint();
        cBodyPanel.revalidate();
    }

    private void loadCarBodyPanel2(Integer carId) {
        cBodyPanel.removeAll();
        CarBodyPanel2 carBodyPanel2 = new CarBodyPanel2(carId);
        carBodyPanel2.setSize(cBodyPanel.getWidth(), cBodyPanel.getHeight());
        cBodyPanel.add(carBodyPanel2);
        cBodyPanel.repaint();
        cBodyPanel.revalidate();
    }

    private void loadCarTable() {

        switch (jComboBox1.getSelectedIndex()) {

            case 1:

                String[] columns = {"ID", "Vehicle No", "Category ID", "Model", "Brand", "Chassis No"};
                DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };
                carTable.setModel(dtm);

                ArrayList<CarDto> carDtos;
                try {
                    carDtos = carController.getRentedCars();
                    for (CarDto carDto : carDtos) {
                        Object[] rowData = {carDto.getVehicleId(), carDto.getVehicleNumber(), carDto.getCarCategoryEntity().getCategoryId(), carDto.getModel(), carDto.getBrand(), carDto.getChassisNo()};
                        dtm.addRow(rowData);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(CarPanel.class.getName()).log(Level.SEVERE, null, ex);
                }

                break;

            case 2:

                String[] columns3 = {"ID", "Vehicle No", "Category ID", "Model", "Brand", "Year", "Colour", "PricePerDay"};
                DefaultTableModel dtm3 = new DefaultTableModel(columns3, 0) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };
                carTable.setModel(dtm3);

                ArrayList<CarDto> carDtos3;
                try {
                    carDtos3 = carController.getAvailableCars();
                    for (CarDto carDto : carDtos3) {
                        Object[] rowData = {carDto.getVehicleId(), carDto.getVehicleNumber(), carDto.getCarCategoryEntity().getCategoryId(), carDto.getModel(), carDto.getBrand(), carDto.getYear(), carDto.getColour(), carDto.getPricePerDay()};
                        dtm3.addRow(rowData);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(CarPanel.class.getName()).log(Level.SEVERE, null, ex);
                }

                break;

            default:

                String[] columns1 = {"ID", "Vehicle No", "Category ID", "Model", "Brand", "Year", "Colour", "Chassis No", "PricePerDay"};
                DefaultTableModel dtm1 = new DefaultTableModel(columns1, 0) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };
                carTable.setModel(dtm1);

                ArrayList<CarDto> carDtos1;

                try {
                    carDtos1 = carController.getAllCars();
                    for (CarDto carDto : carDtos1) {
                        Object[] rowData = {carDto.getVehicleId(), carDto.getVehicleNumber(), carDto.getCarCategoryEntity().getCategoryId(), carDto.getModel(), carDto.getBrand(), carDto.getYear(), carDto.getColour(), carDto.getChassisNo(), carDto.getPricePerDay()};
                        dtm1.addRow(rowData);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(CarPanel.class.getName()).log(Level.SEVERE, null, ex);
                }

        }

    }

    private Integer getCarId() {
        Integer carId = (Integer) carTable.getValueAt(carTable.getSelectedRow(), 0);
        return carId;
    }

    private void deleteCar() {
        Integer carId = 0;
        try {
            carId = getCarId();
            if (carId != 0) {
                try {

                    //Integer carId = getCarId();
                    String result = carController.deleteCar(carId.toString());
                    JOptionPane.showMessageDialog(this, result);
                    loadCarTable();
                } catch (Exception ex) {
                    Logger.getLogger(CarPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a Car from the table before delete");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please select a Car from the table before delete");
        }

    }
}
